### ISSUE TITLE
Point Cloud 𝑷𝒕=0是同时包含手和物体吗？

### ISSUE THREAD

**Issue by guoqingMeng** [PKU-EPIC/UniDexGrasp2#7]
Point Cloud 𝑷𝒕=0是同时包含手和物体吗？𝑷𝒕论文中提到是包含手和物体的点云。
我理解𝑷𝒕=0应该包括手和物体的点云。想确认一下

**Comment by wkwan7** [comment]
是同时包含手和物体，但由于手的初始位置在我们的训练过程中是固定的在物体上方的一个位置，并不能提供额外的有效信息，所以实际处理过程中只使用物体的点云就够了。
